baseURL = 'https://evillogic.github.io'
languageCode = 'en-us'
title = 'infosec blog'
theme = 'risotto'

# Copied from the example site
author = "Kaz Bishop"
copyright = "© 2022 Kaz Bishop"
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "wooper"
mode = "wooper-mode"

# Sidebar: about/bio
[params.about]
title = "infosec blog"
description = "Thoughts and notes on security topics"
logo = "images/rice.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 5 <https://fontawesome.com/> ('fas fa-' or 'fab-fa' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/evillogic"

[[params.socialLinks]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:evillogic1@gmail.com"

[[params.socialLinks]]
icon = "ai ai-arxiv"
title = "Hacking"
url = "javascript:alert('Happy hacking!');"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
